M/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('account/', include('account.urls',namespace='account')),
]

account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>', views.UserProfileView.as_view(), name='user_profile'),
    path('reset/', views.UserPasswordView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.UserPasswordCompleteView.as_view(), name='password_reset_complete'),
    path('follow/<int:user_id>', views.UserFollowing.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>', views.UserUnfollow.as_view(), name='user_unfollow'),
    path('edit/', views.EditProfileView.as_view(), name='edit_user'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('post/detail/<int:post_id>/<slug:post_slug>', views.HomeDetailView.as_view(), name='detail_home'),
    path('post/delete/<int:post_id>', views.DeletePostView.as_view(), name='delete_post'),
    path('post/update/<int:post_id>', views.UpdatePostView.as_view(), name='update_post'),
    path('post/create', views.CreatePost.as_view(), name='create_post'),
    path('reply/<int:post_id>/<int:comment_id>', views.PostAddReply.as_view(), name='add_reply'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    titel = models.CharField(max_length=100)
    body = models.TextField()
    slug = models.SlugField()
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created', '-updated']

    def __str__(self):
        return f'{self.slug} - {self.updated}'

    def get_absolute_url(self):
        return reverse('home:detail_home', args=(self.id, self.slug))


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomment')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcomment')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='rcomment', blank=True, null=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.body[:30]}'

home/forms.py
from django import forms
from .models import Post, Comment

class CreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('titel', 'body')
        labels = {
            'titel': 'Titel'
        }


class CreateCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control'})
        }
        labels = {
            'body': 'سوالات'
        }

class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control'})
        }
        labels = {
            'body': 'ارسال نظر'
        }

class SearchForm(forms.Form):
    search = forms.CharField(label='',widget=forms.TextInput(attrs={'placeholder': 'search'}))

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views import View
from .models import Post, Comment
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .forms import CreateUpdateForm, CreateCommentForm, CommentReplyForm, SearchForm
from django.utils.text import slugify
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
class HomeView(View):
    form_class = SearchForm
    def get(self, request):
        posts = Post.objects.all()
        if request.GET.get('search'):
            posts = posts.filter(titel__contains=request.GET['search'])
        return render(request, 'home/index.html', {'posts': posts, 'search_form': self.form_class})

class HomeDetailView(View):
    form_class = CreateCommentForm
    form_class_reply = CommentReplyForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, pk=kwargs['post_id'], slug=kwargs['post_slug'])
        super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        comments = self.post_instance.pcomment.filter(is_reply=False)
        return render(request, 'home/detail.html', {'post': self.post_instance, 'comments': comments, 'form': self.form_class,'reply_form': self.form_class_reply})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = self.post_instance
            new_comment.save()
            messages.success(request, 'سوال شما ثبت شد', 'success')
            return redirect('home:detail_home', post_id=self.post_instance.id, post_slug=self.post_instance.slug)
class DeletePostView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = Post.objects.get(pk=post_id)
        if post.user.id == request.user.id:
            post.delete()
            messages.success(request, 'تور شمل حذف شد', 'success')
        else:
            messages.error(request, 'شما نمیتوانید این پست را حذف کنید', 'danger')
        return redirect('home:home')

class UpdatePostView(LoginRequiredMixin, View):
    from_class = CreateUpdateForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = Post.objects.get(pk=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        if not post.user.id == request.user.id:
            messages.error(request, 'شما نمیتوانید این پست این پست را حذف کنید', 'danger')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)
    def get(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.from_class(instance=post)
        return render(request, 'home/update.html', {'form': form})

    def post(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.from_class(request.POST, instance=post)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.save()
            messages.success(request, 'پست بروزرسانی شد', 'success')
            return redirect('home:detail_home', new_post.id, new_post.slug)

class CreatePost(LoginRequiredMixin, View):
    form_class = CreateUpdateForm
    def get(self, request):
        form = self.form_class
        return render(request, 'home/create.html', {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.user = request.user
            new_post.save()
            messages.success(request, 'تور ساخته شد', 'success')
            return redirect('home:detail_home', new_post.id, new_post.slug)




class PostAddReply(LoginRequiredMixin, View):
    form_class = CommentReplyForm

    def post(self, request, post_id, comment_id):
        post = get_object_or_404(Post, id=post_id)
        comment = get_object_or_404(Comment, id=comment_id)
        form = CommentReplyForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.post = post
            reply.reply = comment
            reply.is_reply = True
            reply.save()
        return redirect('home:detail_home', post.id, post.slug)

home/templates/home/create.html
{% extends 'base.html' %}


{% block content %}

    <form class="left-align" action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Create">
    </form>



{% endblock %}

home/templates/home/detail.html
{% extends 'base.html' %}

{% block content %}

  {% if request.user.id == post.user.id %}
    <a href="{% url 'home:delete_post' post.id %}" class="btn btn-danger">حذف تور</a>
    <a href="{% url 'home:update_post' post.id %}" class="btn btn-info">بروزرسانی تور</a>
  {% endif %}

  <p><a href="{% url 'account:user_profile' post.user.id %}"> {{post.user.username}}</a> - {{post.updated|date:"Y-M"}}</p>
  <p>{{ post.body }}</p><hr>

  {% if request.user.is_authenticated %}
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="ارسال">
    </form><br>
  {% else %}
    <p class="alert alert-danger">فقط کاربران سایت قابلیت کامنت گذاشتن را دارند</p>
  {% endif %}

  <p>{{ comments.count }} کامنت</p>
  {% for cmt in comments %}
    <div class="card bg-dark text-white">
        <p class="card-header">{{ cmt.user }} | {{ cmt.created|timesince }} ago</p>
        <p class="card-body">{{ cmt.body }}</p>

        <button class="btn btn-primary" onclick="showReplyForm('{{ cmt.id }}')">Reply</button>
        <div id="form_reply_{{ cmt.id }}" {% if request.user.is_authenticated %}style="display: block;"{% else %}style="display: none;"{% endif %}>
          <form action="{% url 'home:add_reply' post.id cmt.id %} " method="post">
              {% csrf_token %}
              {{ reply_form.as_p }}
              <input type="submit" value="Send">
          </form>
        </div>

        {% with replies=cmt.rcomment.all %}
          {% for reply in replies %}
            <p class="bg-primary p-3 m-2">{{reply.user}} <br> {{ reply.body }}</p>
          {% endfor %}
        {% endwith %}
    </div><br>
  {% empty %}
    <p>No comments yet!</p>
  {% endfor %}

  <script>
    function showReplyForm(cmtId) {
      var formReply = document.getElementById("form_reply_" + cmtId);
      if (formReply.style.display === "none") {
        formReply.style.display = "block";
      } else {
        formReply.style.display = "none";
      }
    }
  </script>

{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}

{% block content %}
    <form class="left-align" action="" method="get">
        <div style="display: flex;">
            {{ search_form.search }}
            <input class="btn btn-secondary active" type="submit" value="Search">
        </div>
    </form><br><br>




    <div class="card">
        {% for pst in posts %}
        <a href="{{ pst.get_absolute_url }}" class="card-body"> {{ pst.titel|truncatewords:20 }} </a>
        {% endfor %}
    </div>
{% endblock %}

home/templates/home/update.html
{% extends 'base.html' %}


{% block content %}

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="update">
    </form>



{% endblock %}