M/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('account/', include('account.urls',namespace='account')),
]

account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>', views.UserProfileView.as_view(), name='user_profile'),
    path('reset/', views.UserPasswordView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.UserPasswordCompleteView.as_view(), name='password_reset_complete'),
    path('follow/<int:user_id>', views.UserFollowing.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>', views.UserUnfollow.as_view(), name='user_unfollow'),
    path('edit/', views.EditProfileView.as_view(), name='edit_user'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('post/detail/<int:post_id>/<slug:post_slug>', views.HomeDetailView.as_view(), name='detail_home'),
    path('post/delete/<int:post_id>', views.DeletePostView.as_view(), name='delete_post'),
    path('post/update/<int:post_id>', views.UpdatePostView.as_view(), name='update_post'),
    path('post/create', views.CreatePost.as_view(), name='create_post'),
    path('reply/<int:post_id>/<int:comment_id>', views.PostAddReply.as_view(), name='add_reply'),
]

templates/inc/messages.html
{% if messages %}

  {% for msg in messages %}
    <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
  {% endfor %}

{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="navbar-collapse justify-content-end">
      <ul class="navbar-nav">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'account:user_logout' %}">خروج</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'account:user_profile' request.user.id %}">پروفایل</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'account:user_register' %}">ثبت نام</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'account:user_login' %}">ورود</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'home:home' %}">صفحه اصلی</a>
        </li>
      </ul>
    </div>
  </div>
</nav>